// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3LYYU_zb97NkpG1MbusYstE9CLb45sWo',
    appId: '1:471004099824:web:553549a774a8ae96497e35',
    messagingSenderId: '471004099824',
    projectId: 'aditya-kirana-6fb5b',
    authDomain: 'aditya-kirana-6fb5b.firebaseapp.com',
    storageBucket: 'aditya-kirana-6fb5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK0ZIO84-fCu7ekfmGEn2Gh3oQOCNT6h0',
    appId: '1:331223738086:android:02e73159c8c89b90727d27',
    messagingSenderId: '331223738086',
    projectId: 'kiranastorebuilder-e78dd',
    storageBucket: 'kiranastorebuilder-e78dd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApgk_dVypVY1B7kJ9EGvPmZwLaoj-6Uc',
    appId: '1:471004099824:ios:48a19ba3bc86d237497e35',
    messagingSenderId: '471004099824',
    projectId: 'aditya-kirana-6fb5b',
    storageBucket: 'aditya-kirana-6fb5b.firebasestorage.app',
    iosBundleId: 'com.adityakirana.adityaKirana',
  );
}
